id: DEF725EDD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:47:13+00:00'
last_modified: '2022-05-26T10:43:59.542539+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4be7:
      image_group_id: I1PD95869
      title: རྡོ་རྗེ་མཁའ་འགྲོ་རྣལ་འབྱོར་མའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      order: 24
      base_file: 4be7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
