id: P1D9761BD
initial_creation_type: ocr
source_metadata:
  volumes:
    c78ec7444b434eb6bcb4e7f7bf132fb1:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: རྡོ་རྗེ་མཁའ་འགྲོ་རྣལ་འབྱོར་མའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
